package interfaces;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mekhala Sewwandi
 */
public class HMS_Login extends javax.swing.JFrame {

    /**
     * Creates new form log
     */
    public HMS_Login() {
        initComponents();
    }
    
    LoginPanel logpanel = new LoginPanel();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnReceptionist = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNurse = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 50));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                     HOSPITAL  MANAGEMENT  SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 1400, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/img2.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-10, 80, 1450, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Login As");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 230, 180, 80);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/img3.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 230, 270, 80);

        btnReceptionist.setBackground(new java.awt.Color(255, 255, 255));
        btnReceptionist.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnReceptionist.setForeground(new java.awt.Color(0, 153, 255));
        btnReceptionist.setText("Receptionist");
        btnReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistActionPerformed(evt);
            }
        });
        jPanel1.add(btnReceptionist);
        btnReceptionist.setBounds(1070, 630, 220, 50);
        btnReceptionist.getAccessibleContext().setAccessibleName("btnreceptionist");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/admin icon circle.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 390, 210, 210);

        btnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(0, 153, 255));
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin);
        btnAdmin.setBounds(220, 630, 200, 50);
        btnAdmin.getAccessibleContext().setAccessibleName("btnadmin");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/receptionist icon circle.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1070, 390, 210, 210);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/nurse icon circle.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(790, 390, 210, 210);

        btnNurse.setBackground(new java.awt.Color(255, 255, 255));
        btnNurse.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnNurse.setForeground(new java.awt.Color(0, 153, 255));
        btnNurse.setText("Nurse");
        btnNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseActionPerformed(evt);
            }
        });
        jPanel1.add(btnNurse);
        btnNurse.setBounds(800, 630, 200, 50);
        btnNurse.getAccessibleContext().setAccessibleName("btnnurse");

        btnDoctor.setBackground(new java.awt.Color(255, 255, 255));
        btnDoctor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDoctor.setForeground(new java.awt.Color(0, 153, 255));
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoctor);
        btnDoctor.setBounds(520, 630, 200, 50);
        btnDoctor.getAccessibleContext().setAccessibleName("btndoctor");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/doc login icon.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(510, 390, 210, 210);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/img1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 810);

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 60, 1430, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        
        logpanel.setVisible(true);
        String name = "DOCTOR LOGIN PANEL";
        logpanel.lblPanelName.setText(name);
        this.dispose();
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseActionPerformed
        
        this.setVisible(false);
        logpanel.setVisible(true);
        String name = "NURSE LOGIN PANEL";
        logpanel.lblPanelName.setText(name);
    }//GEN-LAST:event_btnNurseActionPerformed

    private void btnReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistActionPerformed
       
        logpanel.setVisible(true);
        String name = "RECEPTIONIST LOGIN PANEL";
        logpanel.lblPanelName.setText(name);
        this.dispose();
    }//GEN-LAST:event_btnReceptionistActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
    
        logpanel.setVisible(true);
        String name = "ADMIN LOGIN PANEL";
        logpanel.lblPanelName.setText(name);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMS_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMS_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMS_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMS_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HMS_Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnNurse;
    private javax.swing.JButton btnReceptionist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
