package interfaces;



import interfaces.HMS_Login;
import javax.swing.JOptionPane;
import Details.UserDetails;
import GetSet.Occupation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mekhala Sewwandi
 */
public class LoginPanel extends javax.swing.JFrame {

    public LoginPanel() {
        //setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        txtpassword.setEchoChar('\u25CF');
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        lblPanelName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 50));

        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                     HOSPITAL  MANAGEMENT  SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 1150, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/img2.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-10, 80, 1450, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/circle-cropped.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 230, 70, 70);

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtpassword);
        txtpassword.setBounds(680, 500, 240, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Login Here");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(560, 230, 250, 70);

        lblPanelName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPanelName.setForeground(new java.awt.Color(0, 153, 255));
        lblPanelName.setText("LOGIN PANEL");
        jPanel1.add(lblPanelName);
        lblPanelName.setBounds(560, 290, 370, 70);
        lblPanelName.getAccessibleContext().setAccessibleName("");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/username.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(560, 380, 80, 80);

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtusername);
        txtusername.setBounds(680, 400, 240, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/password.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 480, 80, 80);

        btnLogin.setBackground(new java.awt.Color(0, 153, 255));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(780, 620, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/images/docBackground.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        this.dispose();
        HMS_Login log = new HMS_Login();
        log.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String username;
        char[] password;
        String pwrd;
        
        username = txtusername.getText();
        password = txtpassword.getPassword();
        pwrd = new String(password);
        
        UserDetails ud = new UserDetails();
        Occupation ut = ud.finduser(username);
        
        if(ut.getUsername().equals(username) && ut.getPassword().equals(pwrd))
        {
            switch (ut.getOccupation()) {
                case "Doctor":
                    if(lblPanelName.getText().equals("DOCTOR LOGIN PANEL"))
                    {
                        DoctorPanel dp = new DoctorPanel(ut.getId());
                        dp.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
                        txtusername.setText(null);
                        txtpassword.setText(null);
                    }
                     break;
                case "Nurse":
                    if(lblPanelName.getText().equals("NURSE LOGIN PANEL"))
                    {
                        NursePanel np = new NursePanel();
                        np.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
                        txtusername.setText(null);
                        txtpassword.setText(null);
                    }
                    break;
                case "Admin":
                    if(lblPanelName.getText().equals("ADMIN LOGIN PANEL"))
                    {
                        HMS_AdminPanel ap = new HMS_AdminPanel();
                        ap.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
                        txtusername.setText(null);
                        txtpassword.setText(null);
                        
                    }
                    break;
                case "Receptionist":
                    if(lblPanelName.getText().equals("RECEPTIONIST LOGIN PANEL"))
                    {
                        ReceptionistPanel rp = new ReceptionistPanel();
                        rp.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid Username or Password");
                        txtusername.setText(null);
                        txtpassword.setText(null);
                    }
                    break;
            } 
        }
        else{
            
             JOptionPane.showMessageDialog(this, "Invalid Username or Password");
             txtusername.setText(null);
             txtpassword.setText(null);
        }
        
        
       
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblPanelName;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
